article_app/urls.py
from django.urls import path, include, re_path
from .views import *

urlpatterns = [
    path('', main_page, name='main_page'),
    path('contact/', contact, name='contact'),
    path('technical_support/', technical_support, name='technical_support'),
    path('about_journal/', about_journal, name='about_journal'),
    path('editor_board/', editor_board, name='editor_board'),
    path('guide_for_authors/', guide_for_authors, name='guide_for_authors'),
    path('load_sidebar_menus/', load_sidebar_menus, name='load_sidebar_menus'),
    path('load_navbar_menus/', load_navbar_menus, name='load_navbar_menus'),

    path('article/create/', create_article, name='create_article'),
    path('article/view/<int:pk>/', article_view, name='article_view'),
    path('article/edit/<int:pk>/', update_article, name='update_article'),
    path('article/delete/<int:pk>/', delete_article, name='delete_article'),
    path('article/file/create/<int:pk>/', create_article_file, name='create_article_file'),

    path('authors/<int:pk>/', get_article_authors, name='get_article_authors'),
    path('author/add/<int:pk>/', add_author, name='add_author'),
    path('author/edit/<int:pk>/', edit_author, name='edit_author'),
    path('author/delete/<int:pk>/', delete_author, name='delete_author'),

    path('send_message/<int:pk>/<int:user_id>/', send_message, name='send_message'),

    path('sections/', list_sections, name='sections'),
    path('sections/create/', create_section, name='create_section'),
    path('sections/edit/<int:pk>/', edit_section, name='edit_section'),
    path('sections/delete/<int:pk>/', delete_section, name='delete_section'),

    path('article_types/', article_type_list, name='article_types'),
    path('article_types/create/', create_article_type, name='create_article_type'),
    path('article_types/edit/<int:pk>/', edit_article_type, name='edit_article_type'),
    path('article_types/delete/<int:pk>/', delete_article_type, name='delete_article_type'),

    path('article_stages/', article_stages_list, name='article_stages'),
    path('article_stages/create/', create_stage, name='create_stage'),
    path('article_stages/edit/<int:pk>/', edit_stage, name='edit_stage'),
    path('article_stages/delete/<int:pk>/', delete_stage, name='delete_stage'),

    path('article_status/', article_status_list, name='article_status'),
    path('article_status/create/', create_article_status, name='create_article_status'),
    path('article_status/edit/<int:pk>/', edit_article_status, name='edit_article_status'),
    path('article_status/delete/<int:pk>/', delete_article_status, name='delete_article_status'),

    path('notification_status/', notification_status_list, name='notification_status'),
    path('notification_status/create/', create_notification_status, name='create_notification_status'),
    path('notification_status/edit/<int:pk>/', edit_notification_status, name='edit_notification_status'),
    path('notification_status/delete/<int:pk>/', delete_notification_status, name='delete_notification_status'),

    path('last_journal/', last_journal, name='last_journal'),

]

config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

# 1. i18n URL (til prefiksisiz) - TO'G'RI
urlpatterns = [
    path('ax_clone_site/i18n/', include('django.conf.urls.i18n')),
]

# 2. Media va Static (til prefiksisiz)
urlpatterns += [
    re_path(r'^ax_clone_site/media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^ax_clone_site/static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

# 3. Barcha boshqa URL'lar (til prefiksli)
urlpatterns += i18n_patterns(
    path('ax_clone_site/admin/', admin.site.urls),
    path('ax_clone_site/captcha/', include('captcha.urls')),
    path('ax_clone_site/', include('article_app.urls')),
    path('ax_clone_site/profile/', include('user_app.urls')),
    path('ax_clone_site/journal/', include('journal.urls')),
    path('ax_clone_site/post/', include('post.urls')),
    path('ax_clone_site/fileapp/', include('fileapp.urls')),
    path('ax_clone_site/test_maker/', include('test_maker.urls')),
    path('ax_clone_site/expert/', include('expert.urls')),
    path('ax_clone_site/moderator/', include('moderator.urls')),
    path('ax_clone_site/question/', include('question.urls')),
    path('ax_clone_site/pupil/', include('pupil.urls')),
    path('ax_clone_site/exam/', include('exam.urls')),
    path('ax_clone_site/admin1/', include('admin1.urls')),
    path('ax_clone_site/ckeditor/', include('ckeditor_uploader.urls')),
    prefix_default_language=False,
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'user_app.views.error_404'
handler500 = 'user_app.views.error_500'

exam/urls.py
from django.urls import path
from exam.views import *

urlpatterns = [
    path('test_detail/<int:qbox_id>/', test_detail, name='test_detail'),
    path('create_exam/<int:qbox_id>/', create_exam, name='create_exam'),
    path('exam_room/<int:pk>/', exam_room, name='exam_room'),
    path('load_questions/', load_questions, name='load_questions'),
    path('load_questions/<int:pk>/', get_question, name='get_question'),
    path('timer_view/<int:pk>/', timer_view, name='timer_view'),
    path('next_question/', next_question, name='next_question'),
    path('set_cookie_view/', set_cookie_view, name='set_cookie_view'),
    path('delete_cookie_view/', delete_cookie_view, name='delete_cookie_view'),
    path('exam_finished/<int:pk>/', exam_finished, name='exam_finished'),
    path('exam_finish_btn/<int:pk>/', exam_finish_btn, name='exam_finish_btn'),
    path('exam_result/<int:pk>/', exam_result, name='exam_result'),
    path('exam_result_dash/<int:pk>/', exam_result_dash, name='exam_result_dash'),
    path('appeal/', appeals, name='appeals'),
    path('appeal/<int:pk>/', appeal, name='appeal'),
]

article_app/models.py
import os
import re
import time
from django.core.validators import FileExtensionValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class Section(models.Model):
    name = models.CharField(_('Name'), max_length=150, blank=True, default=None)
    key = models.PositiveSmallIntegerField(default=0)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class ArticleType(models.Model):
    name = models.CharField(_('Name'), max_length=150, blank=True, default=None)
    key = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.name


class ArticleLanguage(models.Model):
    name = models.CharField(_('Name'), max_length=150, blank=True, default=None)
    key = models.CharField(max_length=10, blank=True, null=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Stage(models.Model):
    name = models.CharField(_('Name'), max_length=100, default=None)
    key = models.PositiveSmallIntegerField(default=0)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class ArticleStatus(models.Model):
    name = models.CharField(max_length=100, default=None)
    stage = models.ForeignKey('article_app.Stage', on_delete=models.CASCADE, blank=True, null=True)
    key = models.PositiveSmallIntegerField(default=0)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name


def upload_to_file(instance, filename):
    time_sec = int(time.time())
    ext = filename.split('.')[-1]
    filename_new = f"{instance.article.author.id}{instance.article.id}{time_sec}.{ext}"
    return os.path.join(instance.directory_string_var, filename_new)


class Article(models.Model):
    article_type = models.ForeignKey('article_app.ArticleType', on_delete=models.CASCADE, blank=True)
    country = models.ForeignKey('user_app.Country', on_delete=models.CASCADE, blank=True)
    article_lang = models.ForeignKey('article_app.ArticleLanguage', on_delete=models.CASCADE, blank=True)
    section = models.ForeignKey('article_app.Section', verbose_name="Section", related_name="article_section",
                                on_delete=models.CASCADE, blank=True)
    author = models.ForeignKey('user_app.User', on_delete=models.CASCADE, related_name="article_author", blank=True)
    file = models.ForeignKey('article_app.ArticleFile', related_name="article_file", blank=True,
                             on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=255, blank=True)
    abstract = models.TextField(blank=True)
    keywords = models.TextField(blank=True)
    title_en = models.CharField(max_length=255, blank=True)
    abstract_en = models.TextField(blank=True)
    keywords_en = models.TextField(blank=True)
    article_status = models.ForeignKey('article_app.ArticleStatus', on_delete=models.CASCADE, blank=True, null=True)
    is_publish = models.BooleanField(default=False)
    is_resubmit = models.BooleanField(default=False)
    is_publish_journal = models.BooleanField(default=False)
    is_checked_upload_file = models.BooleanField(default=False)
    checked_upload_file = models.FileField(_("Pdf Fayl"), upload_to='uploads/', blank=True, null=True,
                                           validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    filePDF = models.FileField(_("Pdf Fayl"), upload_to=upload_to_file, blank=True, null=True,
                               validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    start_page = models.PositiveBigIntegerField(default=0)
    end_page = models.PositiveBigIntegerField(default=0)
    order_page = models.IntegerField(default=0)
    year = models.IntegerField(default=0)
    number = models.IntegerField(default=0)

    # abstract_text = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-id']


class ArticleFile(models.Model):
    article = models.ForeignKey('article_app.Article', on_delete=models.CASCADE, blank=True)
    file = models.FileField(_("Word, Pdf Fayl"), upload_to=upload_to_file, max_length=255, blank=True,
                            validators=[FileExtensionValidator(allowed_extensions=['doc', 'docx'])],
                            help_text='Please upload only .doc or .docx or files!')
    directory_string_var = 'files/articles/'
    file_status = models.SmallIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def file_name(self):
        return str(self.file.name.split("/")[-1])

    def file_size(self):
        return self.file.size

    def file_type(self):
        name, type_f = os.path.splitext(self.file.name)
        return type_f

    # def get_absolute_url(self):
    #     return reverse('article_app:document-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.article)


class ExtraAuthor(models.Model):
    article = models.ForeignKey('article_app.Article', on_delete=models.CASCADE, blank=True)
    lname = models.CharField(max_length=50, blank=True)
    fname = models.CharField(max_length=50, blank=True)
    mname = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(blank=True)
    work = models.CharField(max_length=255, blank=True, null=True)
    scientific_degree = models.ForeignKey('user_app.ScientificDegree', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.fname


class NotificationStatus(models.Model):
    name = models.CharField(_('Name'), max_length=50, blank=True)

    def __str__(self):
        return self.name


class Notification(models.Model):
    article = models.ForeignKey('article_app.Article', on_delete=models.CASCADE, blank=True)
    from_user = models.ForeignKey('user_app.User', on_delete=models.CASCADE, related_name="sender_user", blank=True,
                                  null=True)
    to_user = models.ForeignKey('user_app.User', on_delete=models.CASCADE, related_name="recieve_user", blank=True,
                                null=True)
    message = models.TextField(_("Message"), blank=True)
    notification_status = models.ForeignKey('article_app.NotificationStatus', on_delete=models.CASCADE, blank=True,
                                            null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_update_article = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

templates/article_app/crud/comment.html
{% load static %}
{% load i18n %}
<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="col-md-12 col-md-6" id="MessageBoxAuthor">
                    <!-- begin widget-chat -->
                    <div class="m-b-10 m-t-10 f-s-12">
                        <h5 class="text-inverse">{% trans "Yozishmalar" %}</h5>
                    </div>

                    <div class="widget-chat widget-chat-rounded m-b-30 forshadow" data-id="widget">

                        <!-- begin widget-chat-header -->
                        <div class="widget-chat-header">
                            <div class="widget-chat-header-icon">
                                <i class="fa fa-file width-30 height-30 f-s-20 bg-yellow text-inverse text-center rounded-corner"
                                   style="line-height: 30px"></i><b>{% trans "Mavzu" %}</b>
                            </div>
                            <div class="widget-chat-header-content">
                                <h4 class="widget-chat-header-title"
                                    id="article_title">{% trans "Ilmiy Markaz" %}</h4>
                            </div>
                        </div>
                        <div class="widget-chat-body" data-scrollbar="true" data-height="250px"
                             id="user_chat_body">


                        </div>

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

templates/article_app/crud/create_article.html
{% load i18n %}
{% load static %}
<form class="create_article_form" method="post" data-url="{% url 'create_article' %}">
    {% csrf_token %}
    {{ form.media }}
    <div class="modal fade" id="create_article_modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{% trans "Maqola qo'shish" %}</h5>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <div class="form-group row m-b-15">
                        <label class="col-md-3 col-sm-3 col-form-label">{% trans "Mamlakat" %} <span
                                class="text-danger">*</span></label>
                        <div class="col-md-9 col-sm-9">
                            {{ form.country }}
                        </div>
                    </div>
                    <div class="form-group row m-b-15">
                        <label class="col-md-3 col-sm-3 col-form-label">{% trans "Tur" %} <span
                                class="text-danger">*</span></label>
                        <div class="col-md-9 col-sm-9">
                            {{ form.article_type }}
                        </div>
                    </div>
                    <div class="form-group row m-b-15">
                        <label class="col-md-3 col-sm-3 col-form-label">{% trans "Til" %} <span
                                class="text-danger">*</span></label>
                        <div class="col-md-9 col-sm-9">
                            {{ form.article_lang }}
                        </div>
                    </div>
                    <div class="form-group row m-b-15">
                        <label class="col-md-3 col-sm-3 col-form-label">{% trans "Rukn" %} <span
                                class="text-danger">*</span></label>
                        <div class="col-md-9 col-sm-9">
                            {{ form.section }}
                        </div>
                    </div>
                    <div class="form-group row m-b-15">
                        <label class="col-md-3 col-sm-3 col-form-label">{% trans "Mavzu" %} <span
                                class="text-danger">*</span></label>
                        <div class="col-md-9 col-sm-9">
                            {{ form.title|safe }}
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-white forshadow" data-dismiss="modal">{% trans "Yopish" %}</a>
                    <button type="submit" class="btn btn-primary forshadow"
                            id="my_article">{% trans "Saqlash" %}</button>
                </div>
            </div>
        </div>
    </div>
</form>
<script src="{% static '/assets/js/demo/form-plugins.demo.js' %}"></script>
<script>
    $(document).ready(function () {
        const $myCreateArticleForm = $('.create_article_form');
        $myCreateArticleForm.submit(function (e) {
            e.preventDefault();

            const $formData = $myCreateArticleForm.serialize();

            let url = $('.create_article_form').data('url');

            $.ajax({
                type: 'POST',
                url: url,
                data: $formData,
                success: function (response) {
                    if (response.result) {
                        $('#create_article_modal').modal('hide');
                        // Validate URL before redirect to prevent open redirect
                        if (response.url && response.url.toString().startsWith('/')) {
                            window.location.href = response.url.toString();
                        }
                    } else {
                        swal({
                            title: response.message,
                            timer: 2000,
                        });
                    }

                },
                error: function (error) {
                    console.log(error);
                }
            });

            return false;
        });
    });
</script>

templates/article_app/crud/create_file.html
{% load i18n %}
{% load static %}
<form data-parsley-validate="true" method="post"
      id="create_articleFile_form"
      data-url="{% url 'create_article_file' article.id %}"
      enctype="multipart/form-data">
    {% csrf_token %}
    <div class="modal fade" id="create_articleFile_modal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{% trans "Fayl yuklash" %}</h5>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>

                <div class="modal-body">
                    <select id="id_article" name="article" class="form-control" style="visibility: hidden">
                        <option selected value="{{ article.id }}"></option>
                    </select>
                    <div class="form-group row m-b-15">
                        <label class="col-md-3 col-sm-3 col-form-label">{% trans "Fayl" %} <span
                                class="text-danger">*</span></label>
                        <div class="col-md-9 col-sm-9">
                            <div class="input-group">
                                <div class="input-group-prepend"></div>
                                {{ form.file }}
                                {% if message %}
                                    <div class="invalid-feedback">{% trans "Fayl yuklashda xatolik mavjud!" %}</div>
                                {% else %}
                                    <div class="valid-feedback">{% trans "Fayl yuklash uchun tayyor!" %}</div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <a class="close btn btn-outline-info" id="createArticleFile_modal"
                       data-dismiss="modal">{% trans "Yopish" %}</a>
                    <button type="submit" class="btn btn-primary submitFileBtn"
                            id="btn_createFile">{% trans "Saqlash" %}</button>
                </div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
    $(document).ready(function () {
        $('#id_file').on('change', function () {
            $('#id_file').addClass("is-valid");
        });

        $('#create_articleFile_form').submit(function (e) {
            e.preventDefault();
            let formData = new FormData(this);
            $.ajax({
                url: "{% url 'create_article_file' article.id %}",
                type: 'POST',
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success: function (response) {
                    if (response.result) {
                        $('#createArticleFile_modal').click();
                        $('#article_file_name').text(response.file_name);
                        swal({
                            title: response.message,
                            timer: 2000,
                        });
                    } else {
                        swal({
                            title: response.message,
                            timer: 2000,
                        });
                    }

                },
            });
        });

    });

</script>

templates/article_app/crud/create_notification_status.html
{% load i18n %}
{% load static %}
<form method="post" data-url="{% url 'create_notification_status' %}" id="create_notification_status_form">
    {% csrf_token %}
    <div class="modal fade" id="create_notification_status_modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{% trans "Yangi xabar holatini qo'shish" %}</h5>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <table id="data-table-default"
                           class="table table-striped table-bordered table-td-valign-middle">
                        <tbody>
                        <tr>
                            <th class="text-nowrap">{% trans "Nomi" %}</th>
                            <td class="text-nowrap">{{ form.name }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-white" data-dismiss="modal">{% trans "Yopish" %}</a>
                    <button type="submit" class="btn btn-primary">{% trans "Saqlash" %}</button>
                </div>
            </div>
        </div>
    </div>
</form>
<script src="{% static '/assets/js/demo/form-plugins.demo.js' %}"></script>

templates/article_app/crud/create_section.html
{% load i18n %}
{% load static %}
<form method="post" data-url="{% url 'create_section' %}" id="create_section_form">
    {% csrf_token %}
    <div class="modal fade" id="create_section_modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{% trans "Yangi rukn qo'shish" %}</h5>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <table id="data-table-default"
                           class="table table-striped table-bordered table-td-valign-middle">
                        <tbody>
                        <tr>
                            <th class="text-nowrap">{% trans "Nomi" %}</th>
                            <td class="text-nowrap">{{ form.name }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-white" data-dismiss="modal">{% trans "Yopish" %}</a>
                    <button type="submit" class="btn btn-primary">{% trans "Saqlash" %}</button>
                </div>
            </div>
        </div>
    </div>
</form>
<script src="{% static '/assets/js/demo/form-plugins.demo.js' %}"></script>

templates/article_app/crud/create_stage.html
{% load i18n %}
{% load static %}
<form method="post" data-url="{% url 'create_stage' %}" id="create_stage_form">
    {% csrf_token %}
    <div class="modal fade" id="create_stage_modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{% trans "Yangi bosqich qo'shish" %}</h5>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <table id="data-table-default"
                           class="table table-striped table-bordered table-td-valign-middle">
                        <tbody>
                        <tr>
                            <th class="text-nowrap">{% trans "Nomi" %}</th>
                            <td class="text-nowrap">{{ form.name }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-white" data-dismiss="modal">{% trans "Yopish" %}</a>
                    <button type="submit" class="btn btn-primary">{% trans "Saqlash" %}</button>
                </div>
            </div>
        </div>
    </div>
</form>
<script src="{% static '/assets/js/demo/form-plugins.demo.js' %}"></script>

templates/article_app/crud/delete_article.html
{% load i18n %}
<form method="post" id="delete_article_form">
{% csrf_token %}
<div class="modal fade" id="delete_article_modal">
    <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">{% trans "Maqolani o'chirish" %}</h4>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <b><i>{{ article.title }}</i></b><br>
                    <hr>
                    <span style="font-size: small">{% trans "Bu maqolani o'chirishga ishonchingiz komilmi?" %}</span>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-white" data-dismiss="modal">{% trans "Yoq" %}</a>
                    <button type="submit" class="btn btn-primary">{% trans "Ha" %}</button>
                </div>
            </div>
    </div>
</div>
</form>
<script>
    $(document).ready(function(){
        const $myRemoveArticleForm = $('#delete_article_form');
        $myRemoveArticleForm.submit(function (e) {
        e.preventDefault();

        const $formData = $myRemoveArticleForm.serialize();

        $.ajax({
            type: 'POST',
            url: "{% url 'delete_article' article.id %}",
            data: $formData,
            success: function (response) {
                $('#delete_article_modal').modal('hide');
                console.log(response);
                if (response.result){
                    swal({
                        title: response.message,
                        timer: 2000,
                    });
                        location.reload(true);
                } else {
                    alert("Xatolik");
                }
                
            },
            error: function (error) {
                console.log(error);
            }
        });

        return false;
    });
    });
</script>

templates/article_app/crud/delete_article_status.html
{% load i18n %}
<div class="modal fade" id="delete_article_status_modal">
    <div class="modal-dialog">
        <form method="post" data-url="{% url 'delete_article_status' article_status.pk %}" id="delete_article_status_form">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">{% trans "Maqola holatini o'chirish" %}</h4>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <strong>{{ article_status.name }}</strong><br>
                    <span style="font-size: small">{% trans "O'chirishga ishonchingiz komilmi?" %}</span>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-white" data-dismiss="modal">{% trans "Yoq" %}</a>
                    <button type="submit" class="btn btn-primary">{% trans "Ha" %}</button>
                </div>

            </div>
        </form>
    </div>
</div>

templates/article_app/crud/delete_article_type.html
{% load i18n %}
<div class="modal fade" id="delete_article_type_modal">
    <div class="modal-dialog">
        <form method="post" data-url="{% url 'delete_article_type' article_type.pk %}" id="delete_article_type_form">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">{% trans "Maqola turini o'chirish" %}</h4>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <strong>{{ article_type.name }}</strong><br>
                    <span style="font-size: small">{% trans "O'chirishga ishonchingiz komilmi?" %}</span>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-white" data-dismiss="modal">{% trans "Yoq" %}</a>
                    <button type="submit" class="btn btn-primary">{% trans "Ha" %}</button>
                </div>

            </div>
        </form>
    </div>
</div>