admin1/urls.py
from django.urls import path
from admin1.views import *

urlpatterns = [
    path('admin1_dashboard/', question_dashboard, name='admin1_dashboard'),
    path('load_questions_admin1/', load_questions_admin1, name='load_questions_admin1'),

    path('question_info/', view_question, name='view_question_admin1'),
    path('question_info/<int:pk>/', question_info, name='question_info_admin1'),

    path('expert_list_admin1/', expert_list_admin1, name='expert_list_admin1'),
    path('load_experts_admin1/', load_experts_admin1, name='load_experts_admin1'),

    path('expert_info/', view_expert, name='view_expert'),
    path('expert_info/<int:pk>/', expert_info, name='expert_info'),
    path('text_to_speech/', text_to_speech, name='text_to_speech'),
    path('load_converted_audios/', load_converted_audios, name='load_converted_audios'),
    path('delete_audio_object/<int:pk>/', delete_audio_object, name='delete_audio_object'),
    path('delete_audio_object/', delete_audio, name='delete_audio'),
    path('generate_text/', generate_text, name='generate_text'),
    path('load_converted_texts/', load_converted_texts, name='load_converted_texts'),
    path('delete_text/<int:pk>/', delete_text_object, name='delete_text_object'),
    path('delete_text/', delete_text, name='delete_text'),
    path('generate_test/', g_test, name='g_test'),
    path('generate_test/<int:pk>/', generate_test, name='generate_test'),
    path('delete_test/<int:pk>/', delete_test, name='delete_test'),

    path('blocking_expert/', blocking_expert, name='blocking_expert'),
    path('blocking_expert/<int:pk>/', blocked_expert, name='blocked_expert'),
    path('un_blocking_expert/', un_blocking_expert, name='un_blocking_expert'),
    path('un_blocking_expert/<int:pk>/', un_blocked_expert, name='un_blocked_expert'),

    path('edit_expert_permission/', edit_expert_permission_url, name='edit_expert_permission_url'),
    path('edit_expert_permission/<int:pk>/', edit_expert_permission, name='edit_expert_permission'),

    path('load_question_count_menu/', load_question_count_menu, name='load_question_count_menu'),
    path('load_sending_question_count_list/', load_sending_question_count_list, name='load_sending_question_count_list'),

    path('load_question_payment_menu/', load_question_payment_menu, name='load_question_payment_menu'),
    path('load_question_payment_list/', load_question_payment_list, name='load_question_payment_list'),
]

config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

# 1. i18n URL (til prefiksisiz) - TO'G'RI
urlpatterns = [
    path('ax_clone_site/i18n/', include('django.conf.urls.i18n')),
]

# 2. Media va Static (til prefiksisiz)
urlpatterns += [
    re_path(r'^ax_clone_site/media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^ax_clone_site/static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

# 3. Barcha boshqa URL'lar (til prefiksli)
urlpatterns += i18n_patterns(
    path('ax_clone_site/admin/', admin.site.urls),
    path('ax_clone_site/captcha/', include('captcha.urls')),
    path('ax_clone_site/', include('article_app.urls')),
    path('ax_clone_site/profile/', include('user_app.urls')),
    path('ax_clone_site/journal/', include('journal.urls')),
    path('ax_clone_site/post/', include('post.urls')),
    path('ax_clone_site/fileapp/', include('fileapp.urls')),
    path('ax_clone_site/test_maker/', include('test_maker.urls')),
    path('ax_clone_site/expert/', include('expert.urls')),
    path('ax_clone_site/moderator/', include('moderator.urls')),
    path('ax_clone_site/question/', include('question.urls')),
    path('ax_clone_site/pupil/', include('pupil.urls')),
    path('ax_clone_site/exam/', include('exam.urls')),
    path('ax_clone_site/admin1/', include('admin1.urls')),
    path('ax_clone_site/ckeditor/', include('ckeditor_uploader.urls')),
    prefix_default_language=False,
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'user_app.views.error_404'
handler500 = 'user_app.views.error_500'

exam/urls.py
from django.urls import path
from exam.views import *

urlpatterns = [
    path('test_detail/<int:qbox_id>/', test_detail, name='test_detail'),
    path('create_exam/<int:qbox_id>/', create_exam, name='create_exam'),
    path('exam_room/<int:pk>/', exam_room, name='exam_room'),
    path('load_questions/', load_questions, name='load_questions'),
    path('load_questions/<int:pk>/', get_question, name='get_question'),
    path('timer_view/<int:pk>/', timer_view, name='timer_view'),
    path('next_question/', next_question, name='next_question'),
    path('set_cookie_view/', set_cookie_view, name='set_cookie_view'),
    path('delete_cookie_view/', delete_cookie_view, name='delete_cookie_view'),
    path('exam_finished/<int:pk>/', exam_finished, name='exam_finished'),
    path('exam_finish_btn/<int:pk>/', exam_finish_btn, name='exam_finish_btn'),
    path('exam_result/<int:pk>/', exam_result, name='exam_result'),
    path('exam_result_dash/<int:pk>/', exam_result_dash, name='exam_result_dash'),
    path('appeal/', appeals, name='appeals'),
    path('appeal/<int:pk>/', appeal, name='appeal'),
]

expert/urls.py
from django.urls import path
from expert.views import *

urlpatterns = [
    # Export dashboard
    path('expert_dashboard/', expert_dashboard, name='expert_dashboard'),
    path('expert_list/', expert_list, name='expert_list'),
    path('expert_list/<int:pk>/', edit_third_expert, name='edit_third_expert'),
    path('get_experts/', get_experts, name='get_experts'),
    path('check_have_certificate/<int:pk>/', check_have_certificate, name='check_have_certificate'),
    path('load_test_for_expert/', load_test_for_expert, name='load_test_for_expert'),
    path('load_test_for_expert/<int:pk>/', check_current_test_expert, name='check_current_test_expert'),
    path('is_have_unchecked_job/', is_have_unchecked_job, name='is_have_unchecked_job'),
    path('load_checked_jobs/', load_checked_jobs, name='load_checked_jobs'),
    path('upload_certificate/', upload_certificate, name='upload_certificate'),
]

admin1/models.py
from django.db import models


# Create your models here.
class Admin1(models.Model):
    user = models.ForeignKey('user_app.User', on_delete=models.CASCADE, blank=True)
    is_admin1 = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.full_name


class TypeVoice(models.Model):
    name = models.CharField(max_length=255)
    key = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.name


class AudioLanguage(models.Model):
    name = models.CharField(max_length=255)
    key = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.name


class HistoryConvertedTextToSpeech(models.Model):
    user = models.ForeignKey('user_app.User', on_delete=models.CASCADE, blank=True)
    text = models.TextField(blank=True)
    type_voice = models.ForeignKey('admin1.TypeVoice', on_delete=models.CASCADE, blank=True)
    language = models.ForeignKey('admin1.AudioLanguage', on_delete=models.CASCADE, blank=True)
    audio_name = models.CharField(max_length=255, blank=True, unique=True)
    audio_file = models.FilePathField(path="speech/")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.audio_name


class TextLanguage(models.Model):
    name = models.CharField(max_length=255)
    key = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.name


class GeneratedText(models.Model):
    user = models.ForeignKey('user_app.User', on_delete=models.CASCADE, blank=True)
    theme = models.CharField(max_length=255, blank=True, null=True)
    word_count = models.PositiveSmallIntegerField(default=0)
    text = models.TextField(blank=True, null=True)
    language = models.ForeignKey('admin1.TextLanguage', on_delete=models.CASCADE, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    test_data = models.TextField(blank=True, null=True)
    is_english = models.BooleanField(default=False)

    def __str__(self):
        return self.theme

expert/forms.py
from django import forms

from expert.models import CheckTestExpert
from django.forms import Select, Textarea, FileInput
from django.utils.translation import gettext_lazy as _


class CheckTestExpertForm(forms.ModelForm):
    class Meta:
        model = CheckTestExpert
        fields = ['message', 'status', 'file']

        widgets = {
            'message': Textarea(attrs={
                'class': 'form-control message',
                'name': 'message',
                'id': 'id_message',
                'rows': '2',
            }),
            'status': Select(attrs={
                'class': 'form-control selectpicker status',
                'data-live-search': "true",
                'data-style': "btn-white",
                'name': 'status',
                'id': 'id_status'
            }),
            'file': FileInput(attrs={
                'class': 'form-control',
                'type': 'file',
                'name': 'file',
                'id': 'id_file',
                'accept': ".docx, .doc,",
            }),
        }

    def __init__(self, *args, **kwargs):
        super(CheckTestExpertForm, self).__init__(*args, **kwargs)
        self.fields['status'].empty_label = _("Tanlang")

templates/admin1/tests.html
{% load i18n %}
{% load static %}

<div class="modal fade viewArticleFont" role="dialog" id="view_test_modal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Test</h3>
                <a href="#" class="close" data-dismiss="modal">&times;</a>
            </div>
            <div class="modal-body" id="textToCopy">
                {% if is_english %}
                    <pre style="font-size: 14px">{{ data }}</pre>
                {% else %}
                    <h2 class="text text-danger">{% trans "Faqat INGLIZ tili uchun ishlaydi!" %}</h2>
                {% endif %}
{#                <h3 class="text text-center text-success">Tez orada ishga tushadi..!</h3>#}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-success" onclick="copyToClipboard()"
                            id="copyToClipboard"><i class="fa fa-copy"></i></button>
{#                {% if not is_empty %}#}
                    <a href="{% url 'delete_test' id %}" class="btn btn-outline-danger"><i class="fa fa-trash"></i></a>
{#                {% endif %}#}
                <button type="button" class="btn btn-outline-dark" data-dismiss="modal"><i class="fa fa-window-close"></i></button>
            </div>
        </div>
    </div>
</div>
<script>
    function copyToClipboard() {
        let textToCopy = document.getElementById("textToCopy");
        let range = document.createRange();
        range.selectNode(textToCopy);
        window.getSelection().removeAllRanges(); // Clear previous selection
        window.getSelection().addRange(range);
        document.execCommand("copy");
        window.getSelection().removeAllRanges(); // Clear selection after copy
        $('#copyToClipboard').css('disabled', 'true')
        swal({
            title: 'Copied!',
            icon: 'success',
            timer: 1000,
        });
    }
</script>

templates/admin1/text_audio_converter_dashboard.html
{% extends 'user_app/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "Konverter" %}{% endblock %}
{% block content %}
    <div id="content" class="content">
        <div class="panel-body forshadow" style="background-color: #ffffff; border-radius: 5px; padding: 2em;">
            <div class="container">
                <form method="post" data-url="{% url 'text_to_speech' %}" id="textToSpeechForm">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        <label for="id_type_voice">{% trans "Ovoz turini tanlang" %}</label>
                        <select class="form-control" id="id_type_voice" name="type_voice">
                            <option value="">{% trans "Tanlang" %}</option>
                            {% for item in  type_voices %}
                                <option value="{{ item.id }}">{{ item.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-6">
                        <label for="id_language">{% trans "Tilni tanlang" %}</label>
                        <select class="form-control" id="id_language" name="language">
                            <option value="">{% trans "Tanlang" %}</option>
                            {% for item in  languages %}
                                <option value="{{ item.id }}">{{ item.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <label for="id_text_string">{% trans "Matnni nusxasini joylashtiring" %}</label>
                    <textarea class="form-control" id="id_text_string" name="text_string" rows="5"></textarea>
                <button type="submit" class="btn btn-outline-primary textToSpeechBtn" style="margin-top: 2%"><img src="{% static 'icons/text-to-speech.png' %}" alt="No icon"> &nbsp;{% trans "CONVERTING" %}</button>
                </form>
                <div id="spinnerDiv" style="display: none">
                    <div class="spinner-grow text-muted"></div>
                    <div class="spinner-grow text-primary"></div>
                    <div class="spinner-grow text-success"></div>
                    <div class="spinner-grow text-info"></div>
                    <div class="spinner-grow text-warning"></div>
                    <div class="spinner-grow text-danger"></div>
                    <div class="spinner-grow text-secondary"></div>
                    <div class="spinner-grow text-dark"></div>
                    <div class="spinner-grow text-light"></div>
                </div>
            </div>
        </div>
    <br>
        <div class="panel-body" style="border-radius: 5px; padding: 2em;">
            <div class="panel-body forshadow" style="background-color: #ffffff; border-radius: 5px; padding: 2em;">
            <div class="table-responsive">
                <table class="table table-bordered table-striped display" id="convertedAudiosTable" style="width:100%">
                    <thead class="table forshadow">
                        <tr class="dataGrid">
                            <th class="align-content-center"><strong>{% trans "ID" %}</strong></th>
                            <th class="align-content-center"><strong>{% trans "Matn" %}</strong></th>
                            <th class="align-content-center"><strong>{% trans "Ovoz turi" %}</strong></th>
                            <th class="align-content-center"><strong>{% trans "Til" %}</strong></th>
                            <th class="align-content-center"><strong>{% trans "Audio fayl" %}</strong></th>
                            <th class="align-content-center"><strong>{% trans "Yaratilgan vaqt" %}</strong></th>
                            <th class="align-content-center"><strong>{% trans "Amal" %}</strong></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            initTable();

            function initTable() {
                let table = $('#convertedAudiosTable').DataTable({
                    columnDefs: [
                        {className: 'dt-center', targets: '_all'},
                    ],
                    destroy: true,
                    ajax: {
                        type: 'POST',
                        url: "{% url 'load_converted_audios' %}",
                        data: {
                            csrfmiddlewaretoken: getCookie('csrftoken')
                        },
                        datatype: "json",
                    },
                    columns: [
                        {data: "id",},
                        {data: "text"},
                        {
                            data: null,
                            bSortable: false,
                            render: function (data, type, row) {
                                let path_audio = data['domain_url'] + data['audio_file'].toString();
                                return `<audio controls><source src="${path_audio}" type="audio/mp3"></audio>`;
                            }
                        },
                        {data: "voice_name"},
                        {data: "language"},
                        {data: "created_at"},
                        {
                            data: null,
                            bSortable: false,
                            render: function (data, type, row) {
                                return '<button type="button" class="btn btn-outline-danger removeAudioBtn" data-id="' + data.id + '"><i class="fa fa-trash" /></button>';
                            }
                        },
                    ],
                    serverSide: true,
                    ordering: true,
                    paging: true,
                    processing: true,
                    info: true,
                    bInfo: true,
                    bSort: true,
                    orderCellsTop: true,
                    fixedHeader: true,
                    order: [],
                });
            }

            $('#convertedAudiosTable tbody').on('click', '.removeAudioBtn', function (e) {
                e.preventDefault();
                let id = $(this).data('id');
                let url = "{% url 'delete_audio' %}"

                $.ajax({
                    type: 'GET',
                    url: '' + url + id + '/',
                    success: function (response) {
                        if (response['result']) {
                            swal({
                                title: 'Muvaffaqiyat!',
                                text: response.message,
                                icon: 'success',
                                timer: 1000,
                            });

                            initTable();

                        } else {
                            swal({
                                title: 'Diqqat!',
                                text: response.message,
                                icon: 'error',
                                timer: 3500,
                            });
                        }
                    },
                    error: function (error) {
                        alert(error);
                    },
                });
            });

            $('body').on('submit', '#textToSpeechForm', function (e) {
                e.preventDefault();

                let formData = new FormData(this);
                let url = $('#textToSpeechForm').data('url');

                $.ajax({
                    type: 'POST',
                    url: url,
                    data: formData,
                    contentType: false,
                    processData: false,
                    beforeSend: function () {
                        $('.textToSpeechBtn').prop('disabled', true);
                        $('#spinnerDiv').css('display', 'block');
                    },
                    success: function (response) {
                        if (response.result) {
                            $('#textToSpeechForm')[0].reset();
                            swal({
                                title: 'Muvaffaqiyat!',
                                text: response.message,
                                icon: 'success',
                                timer: 1500,
                            });
                            initTable();
                        } else {
                            swal({
                                title: 'Diqqat!',
                                text: response.message,
                                icon: 'error',
                                timer: 3500,
                            });
                        }
                    },
                    complete: function (data) {
                        $('.textToSpeechBtn').prop('disabled', false);
                        $('#spinnerDiv').css('display', 'none');
                    },
                    error: function (error) {
                        console.log(error);
                    }
                });
            });

        });
</script>
{% endblock %}

templates/admin1/text_generate_dashboard.html
{% extends 'user_app/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "Text Konverter" %}{% endblock %}
{% block content %}
    <div id="content" class="content">
        <div class="panel-body forshadow viewArticleFont" style="background-color: #ffffff; border-radius: 5px; padding: 2em;">
            <div class="container">
                <form method="post" data-url="{% url 'generate_text' %}" id="generateTextForm">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        <label for="id_language">{% trans "Tilni tanlang" %}</label>
                        <select class="form-control" id="id_language" name="language">
                            <option value="">{% trans "Tanlang" %}</option>
                            {% for item in  languages %}
                                <option value="{{ item.id }}">{{ item.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-6">
                        <label for="id_word_count">{% trans "So'z uzunligi" %}</label><input type="number" min="1" max="500" name="word_count" placeholder="Word count" id="id_word_count" class="form-control">
                    </div>
                    <div class="col-12" style="margin-top: 1%">
                        <div class="note note-info m-b-15" style="height: 50px">
							<div class="note-icon f-s-20">
								<i class="fa fa-lightbulb fa-x"></i>
							</div>
							<div class="note-content">
								<p>Mavzuni kiritayotganizda qaysi til tanlangan bo'lsa shu tilda kiriting.</p>
							</div>
						</div>
                        <label for="id_theme">{% trans "Mavzuni kiriting" %}</label><input type="text" name="theme" placeholder="Mavzuni kiriting" id="id_theme" class="form-control">
                    </div>
                <button type="submit" class="btn btn-outline-primary textGenerateBtn" style="margin-top: 2%"> &nbsp;{% trans "GENERATE TEXT" %}</button>
                </div>
                </form>
                <div id="spinnerDiv" style="display: none">
                    <div class="spinner-grow text-muted"></div>
                    <div class="spinner-grow text-primary"></div>
                    <div class="spinner-grow text-success"></div>
                    <div class="spinner-grow text-info"></div>
                    <div class="spinner-grow text-warning"></div>
                    <div class="spinner-grow text-danger"></div>
                    <div class="spinner-grow text-secondary"></div>
                    <div class="spinner-grow text-dark"></div>
                    <div class="spinner-grow text-light"></div>
                </div>
            </div>
        </div>
    <br>
        <div class="panel-body" style="border-radius: 5px; padding: 2em;">
            <div class="panel-body forshadow" style="background-color: #ffffff; border-radius: 5px; padding: 2em;">
            <div class="table-responsive">
                <table class="table table-bordered table-striped display" id="generateTextTable" style="width:100%">
                    <thead class="table forshadow">
                        <tr class="dataGrid">
                            <th class="align-content-center"><strong>{% trans "Mavzu" %}</strong></th>
                            <th class="align-content-center"><strong>{% trans "Til" %}</strong></th>
                            <th class="align-content-center"><strong>{% trans "Matn" %}</strong></th>
                            <th class="align-content-center"><strong>{% trans "Yaratilgan vaqt" %}</strong></th>
                            <th class="align-content-center"><strong>{% trans "Test yaratish" %}</strong></th>
                            <th class="align-content-center"><strong>{% trans "Amal" %}</strong></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
        <div id="testInfoJson"></div>
    </div>
<script href="https://cdnjs.cloudflare.com/ajax/libs/ace/1.3.3/ace.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            initTable();

            function initTable() {
                let table = $('#generateTextTable').DataTable({
                    columnDefs: [
                        {className: 'dt-justify', targets: '_all'},
                    ],
                    destroy: true,
                    ajax: {
                        type: 'POST',
                        url: "{% url 'load_converted_texts' %}",
                        data: {
                            csrfmiddlewaretoken: getCookie('csrftoken')
                        },
                        datatype: "json",
                    },
                    columns: [
                        {data: "theme"},
                        {data: "language__name"},
                        {data: "text"},
                        {data: "created_at"},
                        {
                            data: null,
                            bSortable: false,
                            render: function (data, type, row) {
                                if (data['language__key'] === 1){
                                    return `<button type="button" class="btn btn-outline-success generateTestBtn" data-id="${data.id}"><i class="fa fa-cloud"></i></button>`;
                                }
                                return ``;
                            }
                        },
                        {
                            data: null,
                            bSortable: false,
                            render: function (data, type, row) {
                                return '<button type="button" class="btn btn-outline-danger removeTextBtn" data-id="' + data.id + '"><i class="fa fa-trash" /></button>';
                            }
                        },
                    ],
                    serverSide: true,
                    ordering: true,
                    paging: true,
                    processing: true,
                    info: true,
                    bInfo: true,
                    bSort: true,
                    orderCellsTop: true,
                    fixedHeader: true,
                    order: [],
                });
            }

            $('#generateTextTable tbody').on('click', '.removeTextBtn', function (e) {
                e.preventDefault();
                let id = $(this).data('id');
                let url = "{% url 'delete_text' %}"

                $.ajax({
                    type: 'GET',
                    url: '' + url + id + '/',
                    success: function (response) {
                        if (response['result']) {
                            swal({
                                title: 'Muvaffaqiyat!',
                                text: response.message,
                                icon: 'success',
                                timer: 1000,
                            });

                            initTable();

                        } else {
                            swal({
                                title: 'Diqqat!',
                                text: response.message,
                                icon: 'error',
                                timer: 3500,
                            });
                        }
                    },
                    error: function (error) {
                        alert(error);
                    },
                });
            });

            $('body').on('submit', '#generateTextForm', function (e) {
                e.preventDefault();

                let formData = new FormData(this);
                let url = $('#generateTextForm').data('url');

                $.ajax({
                    type: 'POST',
                    url: url,
                    data: formData,
                    contentType: false,
                    processData: false,
                    beforeSend: function () {
                        $('.textGenerateBtn').prop('disabled', true);
                        $('#spinnerDiv').css('display', 'block');
                    },
                    success: function (response) {
                        if (response.result) {
                            $('#generateTextForm')[0].reset();
                            swal({
                                title: 'Muvaffaqiyat!',
                                text: response.message,
                                icon: 'success',
                                timer: 1500,
                            });
                            initTable();
                        } else {
                            swal({
                                title: 'Diqqat!',
                                text: response.message,
                                icon: 'error',
                                timer: 3500,
                            });
                        }
                    },
                    complete: function (data) {
                        $('.textGenerateBtn').prop('disabled', false);
                        $('#spinnerDiv').css('display', 'none');
                    },
                    error: function (error) {
                        console.log(error);
                    }
                });
            });

            $('#generateTextTable tbody').on('click', '.generateTestBtn', function (e) {
                e.preventDefault();
                let id = $(this).data('id');
                let url = "{% url 'g_test' %}"

                $.ajax({
                    type: 'GET',
                    url: '' + url + id + '/',
                    success: function (response) {
                        $('#testInfoJson').html(response);
                        $('#view_test_modal').modal({backdrop: 'static', keyboard: false}, 'show');

                    },
                    error: function (error) {
                        alert(error);
                    },
                });
            });

        });

    </script>
{% endblock %}